notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: go
go:
  - "1.10"

install:

script:
  - bash script/test-coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash script/docker-build.sh

deploy:
  provider: script
  script: bash script/docker-push.sh
  on:
    branch: master    