notifications:
  email:
    on_success: never
    on_failure: always

sudo: required

services:
  - docker

language: go
go:
  - "1.10"

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - bash script/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - bash script/Dockerbuild.sh

deploy:
  provider: script
  script: bash script/Dockerpush.sh
  on:
    branch: master    